CREATE DATABASE University

USE University

CREATE TABLE Subjects(
	SubjectID INT PRIMARY KEY,
	SubjectName NVARCHAR(50) NOT NULL,
)

CREATE TABLE Agenda(
	StudentID INT PRIMARY KEY,
	SubjectID INT NOT NULL FOREIGN KEY REFERENCES Subjects(SubjectID)
)

CREATE TABLE Major(
	MajorID INT PRIMARY KEY,
	[Name] NVARCHAR(50) NOT NULL,
)

CREATE TABLE Students(
	StudentID INT NOT NULL FOREIGN KEY REFERENCES Agenda(StudentID),
	StudentNumber CHAR(30) NOT NULL,
	StudentName NVARCHAR(50) NOT NULL,
	MajorID INT NOT NULL FOREIGN KEY REFERENCES major(MajorID)
)

CREATE TABLE Payments(
	PaymentID INT PRIMARY KEY,
	PaymentDate DATE NOT NULL,
	PaymentAmount DECIMAL(12,2),
	StudentID INT NOT NULL FOREIGN KEY REFERENCES Agenda(StudentID)
	)