CREATE DATABASE OnlineStore
USE OnlineStore

CREATE TABLE ItemTypes(
	ItemTypeId INT PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	)

CREATE TABLE Items(
	ItemID INT PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	ItemTypeId INT NOT NULL FOREIGN KEY REFERENCES ItemTypes(ItemTypeId)
	)

CREATE TABLE OrderItems(
	OrderID INT PRIMARY KEY,
	ItemID INT NOT NULL FOREIGN KEY REFERENCES Items(ItemID)
)

CREATE TABLE Orders(
	OrderID INT NOT NULL FOREIGN KEY REFERENCES OrderItems(OrderID),
	CustomerID INT PRIMARY KEY,
	)

CREATE TABLE Customers(
	CustomerID INT NOT NULL FOREIGN KEY REFERENCES Orders(CustomerID),
	[Name] VARCHAR(50) NOT NULL,
	Birthday DATE NOT NULL,
	CityID INT PRIMARY KEY
)

CREATE TABLE Cities(
	CityID INT NOT NULL FOREIGN KEY REFERENCES Customers(CityID),
	[Name] VARCHAR(50)
)

SELECT * FROM ItemTypes
SELECT * FROM Items
SELECT * FROM OrderItems
SELECT * FROM Orders
SELECT * FROM Customers
SELECT * FROM Cities



